### ISSUE TITLE
AMDGPU freeze when opening/manipulating windows

### ISSUE THREAD

**Issue by ghost** [CachyOS/linux-cachyos#221]
Analog to Issue https://github.com/CachyOS/linux-cachyos/issues/219#issue-2099428464 , i have nearly the same issue. When i manipulate (move) or open/close new windows/programs, the system freezes for some time. When checking the system log, entries regarding amdgpu can be found. The screenshot shows the only interesting entries regarding the issue. The freeze only happens on Cachy-Kernels, on Vanilla Arch no such issues happen. Can confirm that a fresh install of the OS won't fix the issue. Same goes for Hardware, my Laptop with a Radeon 680M shows the same issues.

![ps_20240126035634](https://github.com/CachyOS/linux-cachyos/assets/139169579/2e9c2816-10dc-41c8-9c4e-49d746f60480)

Hardware Desktop:
Intel 14900k
MSI Z790P-Pro DDR5 (with installed Dasharo-Coreboot)
Corsair Dominator Platinum 7200MHz DDR5
Samsung 990 Pro 2 TB
AMD Radeon Vega 64

Hardware Laptop:
Lenovo 14ARB7
AMD Ryzen 7 6800U
AMD Radeon 680M
16 Gb LPDDR5 6400

**Comment by lseman** [comment]
Can you confirm the kernel version?

**Comment by K-Fuchs** [comment]
The versions used are linux-cachyos-rc-lto (6.8rc1), linux-cachyos-lto (6.7.1).
I will try the kernel flag and report back.

**Comment by K-Fuchs** [comment]
The freeze still happens with the kernel flag set. 
But i tried different versions of the cachy kernels and the freeze only happens on the LTO kernels.
On the normal kernel versions, the issue does not appear.

**Comment by lseman** [comment]
Just to confirm, since it still happens, but less frequent, in non LTO kernel.
Could you test if it still happens in vanilla, however less frequent too?

**Comment by K-Fuchs** [comment]
I  tried the vanilla arch kernel for about 3-4 hours without any freeze or error messages.  On both computers, as soon as i switch back to the cachy kernels the issue starts happening again.

**Comment by ptr1337** [comment]
Could you provide a "sudo cachyos-bugreport.sh" when this is happening?

We are currently not modify anything on the amdgpu part. Also please check out 6.7.2.
If it is possible install the kernel also from the "cachyos" repo instead of the "cachyos-v3" repository. Maybe the x86-64-v3 instruction set introduces for your vega some issues.

**Comment by K-Fuchs** [comment]
I closed the issue, although it is not resolved. But, i was able to reproduce the issue on vanilla Arch now. On my Laptop and my Desktop. The issues started last week Tuesday Evening - Friday morning after a update. So, i will have a look which packages where updated that time. For now, i switched to Fedora which does not have this issues for now. 

But this issue is not CachyOS related after all. Its either Arch specific, or a recent update of a package twisted something.....

**Comment by K-Fuchs** [comment]
There seems to be an issue somewhere upstream. I reported the bug upstream and will try to narrow the start of the  issue down to a specific kernel version. For now, if someone has the issue using the 6.6 LTS Version will work without errors.

[Upstream Bug Report](https://gitlab.freedesktop.org/drm/amd/-/issues/3138)

**Comment by ptr1337** [comment]
Is this still a issue?
