### ISSUE TITLE
Nobara pollrate patch

### ISSUE THREAD

**Issue by dnodno** [CachyOS/linux-cachyos#240]
add [Nobara pollrate patch](https://github.com/GloriousEggroll/Linux-Pollrate-Patch) for setting custom pollrate of game controllers

**Comment by mastapix** [comment]
I believe that patch also allows Bluetooth polling rate up to 1000hz for DualSense and DS4 controllers. This would be an incredible add to this kernel

**Comment by mcleanbc** [comment]
I started to look into the Nobara patches. There are two we would need to add in:

- A patch specific to the Dualsense bluetooth polling rate: https://github.com/Nobara-Project/rpm-sources/blob/a35a4372fadaf26d79aed94f82df9dc9ae06d4c2/baseos/kernel/6.11/set-ps4-bt-poll-rate-1000hz.patch
- The patch that allows setting a custom USB polling rate, included here: https://github.com/GloriousEggroll/Linux-Pollrate-Patch

I spun up a fork, https://github.com/CachyOS/kernel-patches/compare/master...mcleanbc:kernel-patches:add-usb-dualsense-patches, and used the cachyos Kernel Manager to build a custom 6.11 kernel with these patches without issue.

@ptr1337 would you be open to including either of these in the base patches file, or would you prefer to keep them separate? I can spin up a PR once we decide where it would make sense to include these / whether we would want both enabled by default.

**Comment by ptr1337** [comment]
Sorry, I wont queue the custom pollrate patchset. The DS4 one would be fine.

**Comment by mcleanbc** [comment]
That's reasonable. The USB pollrate patch is much larger and more experimental. 

@ptr1337 I created a PR to add in the DS4 patch for 6.11 and 6.12 base patches, https://github.com/CachyOS/kernel-patches/pull/76 . Would you or another maintainer be able to review?

**Comment by ptr1337** [comment]
Has been queued by naim into our linux tree:
https://github.com/CachyOS/linux/compare/b1d29f313eac...61f1bf8f38d3

**Comment by dnodno** [comment]
sorry to reopen,  How do you enable 1000hz mode for DS4 or is it enabled by default?
if enabled by default is this patch limited to bluetooth connected DS4? EVHZ still reads 250hz for wired DS4 (054c:09cc) on kernel 6.11.6-2-cachyos

**Comment by mcleanbc** [comment]
This patch is limited to bluetooth only.

For USB, you would need to apply this patch: https://github.com/GloriousEggroll/Linux-Pollrate-Patch . As Peter mentioned above, this more experimental patch will not be queued for release, but you could use the Kernel Manager to apply it to your own kernel if you wanted to.

**Comment by ptr1337** [comment]
Hey,

We have reverted the patch again, since GE has reported in the internal nobara chat, that when multiple controller are plugged in, that this cause issues.

Im a bit confused, hwy this should really make a difference, setting the BT Poll to 1000 Hz, but that was the result of the bisection.

**Comment by dnodno** [comment]
> but you could use the Kernel Manager to apply it to your own kernel if you wanted to.

Cachyos kernel manager no longer successfully applies the pollrate patch,  it fails during the initial phase with all other settings being default. the issue started a few releases ago, I'm not 100% but perhaps during the ntsync release 6.14.

Setting custom pollrate still works on Nobara OS with the latest kernel, so i guess the issue is specific to Cachyos.

[console output](https://github.com/user-attachments/files/20961513/output.txt)

**Comment by 1Naim** [comment]
The patch you have is outdated. Get the latest revision of it [here](https://github.com/LionHeartP/rpm-sources/blob/kernel-6.15/baseos/kernel/6.15/0001-Allow-to-set-custom-USB-pollrate-for-specific-device.patch).

**Comment by dnodno** [comment]
> The patch you have is outdated. Get the latest revision of it [here](https://github.com/LionHeartP/rpm-sources/blob/kernel-6.15/baseos/kernel/6.15/0001-Allow-to-set-custom-USB-pollrate-for-specific-device.patch).

Thanks it's compiling now

**Comment by p0358** [comment]
Since Cachy never applied that patch, I made a DKMS module to achieve this: https://github.com/p0358/usb_oc-dkms

EDIT: btw I noticed something problematic in the original patchset:
```diff
+			case USB_SPEED_SUPER_PLUS:
+			case USB_SPEED_SUPER:
+			case USB_SPEED_HIGH:
+				endpoint->desc.bInterval = fls(ival) + 3;
```

The conversion and `+3` was made to make the parameter value be compatible with USB 1.1 values even if you apply them to USB 2.0+ device, but this effectively shields users from being use any modes higher than 1000 Hz (it shadows 2000, 4000, 8000 Hz)...

**Comment by Anuskuss** [comment]
> We have reverted the patch again, since GE has reported in the internal nobara chat, that when multiple controller are plugged in, that this cause issues.

@ptr1337 Sorry for necroing but what was the issue? And can this be turned into a runtime-configurable option? Maybe through kernel parameters or something like a `hid_playstation_1000hz` module?
Currently through testing via [Gamepadla's Polling](https://github.com/cakama3a/Polling) I'm getting 4XX Hz over BT, which points to 2 ms. To me that doesn't make sense because I thought it's supposed to by [4 ms](https://github.com/torvalds/linux/blob/v6.19/drivers/hid/hid-playstation.c#L375), unless CachyOS does something differently here (although I am getting 250 Hz over USB)? Would that change alone even be enough to unlock 1000 Hz (without making additional changes to the BT/USB interface)?

> Since Cachy never applied that patch, I made a DKMS module to achieve this:

@p0358 Thank you for your effort! Would you be able to do something similar for BT? Are does one only need to modify the `hid_playstation` module for that?

**Comment by p0358** [comment]
@Anuskuss I'm reading the source code and it seems that the module is now called `hid-sony` the the BT polling rate should be adjustable, the file `bt_poll_interval` should be created somewhere in /sys while the device is connected and be possible to override its value to 1 to override the polling rate? It seems it's vendor-specific in that the polling rate is passed to the controller to act this way rather than enforced by host like in case of USB. I guess try doing `find /sys -name bt_poll_interval` while the controller is connected...?

**Comment by Anuskuss** [comment]
> I'm reading the source code and it seems that the module is now called `hid-sony`

I think it's actually the opposite: `hid_playstation` is the newer, official one while `hid_sony` is the older, community-developed one.
Also found this [patch](https://patchew.org/linux/20250508214305.836406-1-titanv3585@gmail.com) where `bt_poll_interval`was (supposedly) ported to `hid_playstation` but I can't find it in `/sys`. I could try to blacklist `hid_playstation` so it loads `hid_sony` instead but I'm not even sure if `hid_sony` supports DualSense. Will investigate this more.

**Edit:** DualSense does not work with `hid_sony`.
