### ISSUE TITLE
Feral's gamemode

### ISSUE THREAD

**Issue by nipnipj** [CachyOS/linux-cachyos#264]
Can we use Feral's gamemode when using cachyos kernel? Does it affect it positively? Would you guys recommend not using gamemode?

**Comment by ptr1337** [comment]
Hi,

It depends, if you are on cachyos, then we do not suggest it, since we are using ananicy-cpp for setting the niceness for games.

Aditonally, we have a script called "game-performance %command%", which automatically sets the cpu gov to performance, for enhanced performance. This is in the cachyos-settings package.

 Actually, gamemode doesnt do more - it does renice (which is currently broken) and set the cpu gov to performance.
 As long you dont use customized scripts or configs, then it does not care all too much

**Comment by nipnipj** [comment]
Does this apply for the archlinux users that installed cachyos kernel from aur?

**Comment by ptr1337** [comment]
> Does this apply for the archlinux users that installed cachyos kernel from aur?

This does only apply, when cachyos-settings together with ananicy-cpp is used
