### ISSUE TITLE
cachyos realtime kernel

### ISSUE THREAD

**Issue by hifi25nl** [CachyOS/linux-cachyos#27]
I see that in Archlinux AUR there is a version 5.16 of linux-cachyos-rt
Do you plan to release a version 5.19.x?
(5.16 is not compiling because of missing upstream files)

**Comment by ptr1337** [comment]
> I see that in Archlinux AUR there is a version 5.16 of linux-cachyos-rt Do you plan to release a version 5.19.x? (5.16 is not compiling because of missing upstream files)

Hey!

I've planned to default RT with 6.0 so that it is a option which could be set.
Since there is right now mostly just going on development for the rc/dev kernel, i canceld it so far and just do some testings.

Since it will be offically merged with 6.0/6.1 this will be without all the patching then possible.

**Comment by hifi25nl** [comment]
I have just compiled linux-cachyos with realtime patch.
I had to apply some tweaks, but at last it is working.
Not sure if in this case cfs is the best cpu scheduler

Realtime test was very good. Cpu latency max 4 microseconds and average latency most of time under 1 microseconds

**Comment by ptr1337** [comment]
Yes. As I said, we will implement into the Kernel as soon its Kernel in. Or as soon the 6.1/6.2 development started for the merge into the Kernel into it, we will backport it and put them into the PKGBUILD as option

**Comment by ptr1337** [comment]
I have added for the 6.0 rc Kernel a realtime patch:

https://github.com/CachyOS/kernel-patches/commit/4f064d5da1a14ed705bf8dcda2e1142a0dd6d0cb

We will probably implement a option at the "_preempt=", to enable realtime.
The only issue I see, is that the RT Kernel does need CONFIG_EXPERT in the config, so that it gets enabled. Since we don't use CONFIG_EXPERT as default, there will be a lot of additional config prompts.
So we need to watch how we solve that with the same config in a PKGBUILD.

We will work something out until the 6.0 release. But with the patch you can already test it, simply add the patch to the 6.0 PKGBUILD, then enable "makenconfig" and select in the General Menu PREEMPT_RT.

**Comment by hifi25nl** [comment]
I have successfully compiled 3 realtime kernels with different architecture (ZEN, SKYLAKE, ZEN3)

With kernel 5.19 compilation was stopping at kernel/rcu/rcutorture.c
I had to remove it and the corresponding realtime patch section.

Moreover, I could not find full  RT in menuconfig without enabling embedded system in General Setup
(...long time to find somewhere this suggestion)

NVIDIA drivers are compiling fine, but the system will not boot
The linux-rt package is AUR is working fine with NVIDIA
I would like to know what changes have been made in that package

**Comment by ptr1337** [comment]
I will have a watch how 5.19 does play with. I just checked for 6.0 right now, since the focus in the next weeks will be at 6.0 and then provide RT as default as a option in the PKGBUILD.

You need to enable at the GENERAL Menu first "CONFIG_EXPERT" then you are able to select preempt real time in the preempt config part.

You mean, linux-cachyos + rt patch + nvidia does not boot? I can test this, since I have also a nvidia card in.

**Comment by hifi25nl** [comment]
Yes here linux-cachyos + rt patch + nvidia is not booting

**Comment by hifi25nl** [comment]
This is happening also on xanmod-rt, but not on linux-rt

**Comment by sirlucjan** [comment]
Please try https://github.com/CachyOS/linux-cachyos/commit/d511715ffe3d19835ad0c7380de9e6916b70cad1

**Comment by ptr1337** [comment]
@hifi25nl 
I have just compiled one for ZEN3 with the latest commit we sent. It compiled and booted fine on my 5900x, GTX 1070Ti.
Benchmark's showed so far also a good result.

We just pushed the latest minimal changes, which would make the RT experience better.
Just run `git checkout dev` to test it and use the linux-cachyos-rc and set `_rtkernel=y`.

Feedback would be welcome! Have fun :)

**Comment by hifi25nl** [comment]
Ok good I will try tomorrow

**Comment by sirlucjan** [comment]
You don't need to switch to the dev branch anymore - choose kernel linux-cachyos-rt and proceed as @ptr1337 suggested.

**Comment by hifi25nl** [comment]
I just compiled linux-cachyos-rt 6.0 rc5 successfully.

As all RT kernels are incompatible with virtualbox (virtualbox-host-dkms) I had to remove the drivers from modules-load.d in my installation

This kernel cannot be compiled with lto full (previous 5.19 with RT patch did not have this problem) The error is:
  LD [M]  net/netfilter/nf_flow_table.o
  AR      net/netfilter/built-in.a
  AR      net/built-in.a
==> ERROR: A failure occurred in build().
    Aborting...

Without lto no problems. Performance is very good with very low latency

**Comment by ptr1337** [comment]
> I just compiled linux-cachyos-rt 6.0 rc5 successfully.
> 
> As all RT kernels are incompatible with virtualbox (virtualbox-host-dkms) I had to remove the drivers from modules-load.d in my installation
> 
> This kernel cannot be compiled with lto full (previous 5.19 with RT patch did not have this problem) The error is: LD [M] net/netfilter/nf_flow_table.o AR net/netfilter/built-in.a AR net/built-in.a ==> ERROR: A failure occurred in build(). Aborting...
> 
> Without lto no problems. Performance is very good with very low latency NVIDIA drivers working fine

The virtual box modules is a upstream issue probably with 6.0, and need to get fixed their.
Do you have maybe the log from it? Is the dkms compilation affected from it ?

I dont see a error above in the log you sent, but I run right now a compilation with FULL LTO and will report you.

Glad that he performance is good to you, I had first some issues with a extra real time RCU option, but my complete sound got broken through it and the performance was really bad.

**Comment by hifi25nl** [comment]
Virtual box dkms compiled fine. Only kernel panic at boot if the module is loaded.
About lto full I will wait your compilation.

**Comment by sirlucjan** [comment]
If everything works correctly, you can close the thread.

**Comment by hifi25nl** [comment]
Thanks for support!

**Comment by sirlucjan** [comment]
I'm glad we could help. I had a bit of trouble making sense of the real time kernel build as an option, but it's cool that you liked the end result. And thanks for the suggestion.
