### ISSUE TITLE
AutoFDO & Propeller

### ISSUE THREAD

**Issue by lateautumn233** [CachyOS/linux-cachyos#274]
https://www.phoronix.com/news/AutoFDO-Propeller-Kernel#google_vignette

May I ask if it is possible to add it to the kernel

**Comment by ptr1337** [comment]
> https://www.phoronix.com/news/AutoFDO-Propeller-Kernel#google_vignette
> 
> May I ask if it is possible to add it to the kernel

Patch is already available, but im not able to convert the AutoFDO profile on my Zen4 machine. This anyways requires multiple steps and does not work automatically.

**Comment by ptr1337** [comment]
I had some success using AutoFDO on top of the kernel.

The profiling worked and also I was able to boot into the kernel.
I have used from the kernel tree "make pacman-pkg" to create the kernel and it worked flawless. Im fighting currently a bit integrating it into the PKGBUILD, since as soon a profile is set the packaging fails.

See here:
https://lore.kernel.org/lkml/3183ab86-8f1f-4624-9175-31e77d773699@cachyos.org/

If you want, I can provide some info/tutorial how to use AutoFDO on top of the cachyos kernel with make pacman-pkg

**Comment by ptr1337** [comment]
https://github.com/CachyOS/website/blob/develop/src/content/post/2411-kernel-autofdo.md

Ive created a guide here

**Comment by ptr1337** [comment]
https://github.com/CachyOS/linux-cachyos/pull/322

Its now integrated with a basic integration in the PKGBUILD. Feel free to test.
Propellor is pending.

Be aware to update your system, because it requires a revert in binutils.

**Comment by ptr1337** [comment]
> when will there be a guide on the propeller

I thought about writing one on the weekend based on the PKGBUILD, but it depends how much time I have
