### ISSUE TITLE
Tried CachyOS with the DKE, went back to Windows.

### ISSUE THREAD

**Issue by Destroyarr** [CachyOS/linux-cachyos#278]
The win11 is more graphically and control polished I get better mouse control which makes me feel better at every input and every feedback I get from the system.

My mouse is extreme device with 8Khz polling and 20K dpi signals input.

The Win11 OS they seem to have made a custom acceleration curve which reduce energy expenditure on my part, to move the mouse on every position I need.

Or they made some optimization, I feel they drive mouse cursor more lower level or something?

On the Win 11 I also get perfect scaling in OS , legacy apps and in browser including fonts.

On the Win11 I also get advanced debloating with NTLite which makes the system extreme optimised.

I also get Quake Champions with its anticheat.

In the Linux if we get perfect mouse and perfect graphics, we are in business, right?

**Comment by ptr1337** [comment]
I dont fully understand, why you are posting here an issue?

This is the issuetracker for the kernel, and has nothing to do with your Linux and Windows comparision.
> My mouse is extreme device with 8Khz polling

Depending on, which mouse you have this is also supported.
> 20K dpi signals input.

No idea, why you would use 20k DPI but this is supported on linux

> The Win11 OS they seem to have made a custom acceleration curve which reduce energy expenditure on my part, to move the mouse on every position I need.

????

> On the Win 11 I also get perfect scaling in OS , legacy apps and in browser including fonts.

You have this on linux too

> On the Win11 I also get advanced debloating with NTLite which makes the system extreme optimised.

???

Closing here, since no related.
