### ISSUE TITLE
Making "-lto" package name suffix an option?

### ISSUE THREAD

**Issue by xuanruiqi** [CachyOS/linux-cachyos#36]
Some of us might not like this "-lto" package name suffix that is automatically added to the package name when LTO is enabled in config. For instance, it bothers me a bit since it doesn't really help me and it interferes with AUR helpers, etc., as the package name is absent from the AUR and AUR helpers couldn't detect new versions automatically anymore.

So IMO it makes sense to make the "-lto" name suffix an option that could be disabled.

**Comment by ptr1337** [comment]
Hello,

Actually you are right, that aur helpers can't detect this, but we anyways don't suggest to use a aur helper for building the kernels, since it does bring often issues.

Since the PKGBUILD does already contain that many options, it would be in my eyes a bit bloat.
I talk the next days with @sirlucjan about that.

Pushing additionally 13 aur packages, to support aur helpers at this point, would be also to much.
We will have a look.

**Comment by xuanruiqi** [comment]
I don't use AUR helpers to build kernels, but they're useful to detect updates nonetheless. Same for tools like checkupdates-aur

**Comment by sirlucjan** [comment]
@xuanruiqi 

Does such a change satisfy you? If you can, let us know. 

```From 8410dffbe843151f1087c8f25026f4fea3526e59 Mon Sep 17 00:00:00 2001
From: Piotr Gorski <lucjan.lucjanov@gmail.com>
Date: Thu, 6 Oct 2022 20:33:55 +0200
Subject: [PATCH] add lto suffix

Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>
---
 PKGBUILD | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/PKGBUILD b/PKGBUILD
index d00c631..3eb609a 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -138,6 +138,10 @@ _zstd_level_value=${_zstd_level_value-'normal'}
 # "thin: uses multiple threads, faster and uses less memory, may have a lower runtime performance than Full."
 _use_llvm_lto=${_use_llvm_lto-}
 
+# Use suffix -lto only when requested by the user
+# https://github.com/CachyOS/linux-cachyos/issues/36
+_use_lto_suffix=${_use_lto_suffix-}
+
 # KCFI is a proposed forward-edge control-flow integrity scheme for
 # Clang, which is more suitable for kernel use than the existing CFI
 # scheme used by CONFIG_CFI_CLANG. KCFI doesn't require LTO, doesn't
@@ -180,7 +184,7 @@ _nest=${_nest-}
 # https://gitlab.com/ananicy-cpp/ananicy-cpp/-/tree/feature/latency-nice
 _latency_nice=${_latency_nice-y}
 
-if [ -n "$_use_llvm_lto" ]; then
+if [[ -n "$_use_llvm_lto" && -n "$_use_lto_suffix" ]]; then
     pkgsuffix=${_cpusched}-lto
     pkgbase=linux-$pkgsuffix
 
-- 
2.38.0.rc1.6.g4fd6c5e444```

**Comment by sirlucjan** [comment]
If I could ask you to test and feedback, I would be extremely grateful. As soon as we get feedback, we will make the necessary adjustments.

**Comment by sirlucjan** [comment]
@xuanruiqi Please look at testing branch:

https://github.com/CachyOS/linux-cachyos/commit/703f6599674abcab131bec83d114b1e8f4cca07f

If @ptr1337 accepts the changes and from your side the feedback is positive, I will merge the changes into the master branch.

**Comment by xuanruiqi** [comment]
I've tested and it works for me!

**Comment by sirlucjan** [comment]
Thank you! Great. Now I will wait to @ptr1337 opinion.

**Comment by sirlucjan** [comment]
Merged into master https://github.com/CachyOS/linux-cachyos/commit/a4dba6ee3685aeff6dec1d3789e2093db2876faf

After discussion with @ptr1337 and @vnepogodin, we decided to leave the suffix option on by default due to the fact that it will be more convenient for most users. If someone wants to build a kernel without suffix -lto, all they need to do is remove the "y" before the flag

```
_use_lto_suffix=${_use_lto_suffix-}
```

**Comment by ptr1337** [comment]
Seems good. Ill close here, since it should be solved.
