### ISSUE TITLE
Gentoo ebuild and -O3 kernel patch

### ISSUE THREAD

**Issue by shoober420** [CachyOS/linux-cachyos#8]
I just discovered this modded kernel, and it looks very promising. I currently use the pf kernel patch set (https://gitlab.com/post-factum/pf-kernel/-/wikis/README), but it seems the BMQ CPU scheduler hasn't been updated for 5.16 kernel yet (https://gitlab.com/alfredchen/linux-prjc), at least officially.

I have a couple questions. Does this kernel patch set have or could possibly include the -O3 kernel patch? Also, is there a possible chance you can provide a Gentoo ebuild for this kernel? Lastly, is the BMQ CPU scheduler still considered the fastest, or has it been succeeded by another scheduler?

Thank you

**Comment by ptr1337** [comment]
Hey! 

It is now everything fixed. Im not really into gentoo. But i can provide complete patches + the needed config for it if that helps. 
The kernel does include the -O3 patchset and is also enabled as default at the PKGBUILD. 

The prjc scheduler is maintained by some other people, or better a community patch so far, which runs so far quite good. 

Currently i provide only at arch prebuil kernel with x86-64-v3 and also lto builds. For a ebuild you would need to adjust it. 

I can also provide a normal kernel tree if this helps, since i patch on the stock kernel tree.

Best regards

**Comment by ventureoo** [comment]
To use this in Gentoo you can simply clone the repository and move all the patches to `/etc/portage/patches/sys-kernel/gentoo-sources-5.16.3/`. Portage will apply the patches itself. The only problem may be a lot of manual kernel configuration. Although default configs can also be copied from this repository and placed in `/usr/src/linux/.config`.

See:

https://wiki.gentoo.org/wiki/Epatch#Adding_user_patches
https://wiki.gentoo.org/wiki/Kernel/Configuration/Kernel_Seeds#Configuration

**Comment by ptr1337** [comment]
Hey @shoober420 @ventureoo ,

i will provide here now https://github.com/CachyOS/linux-cachyos/tree/master/patches the complete patches for the kernel, so far i talked with another gentoo user, he said, you guys configure it sofar the kernel yourself.

If not a base config can be found in the in every kernel directory. 

Regards
