### ISSUE TITLE
Asking/recommending a kernel patch

### ISSUE THREAD

**Issue by msmafra** [CachyOS/linux-cachyos#97]
Hello!

I have a Lenovo Legion laptop and in recent months discovered a LenovoLegionLinux kernel patch while testing a version of Nobara in the middle of their list of added features/changes/patches there was one not related to gaming that could be very useful to my system. I use Fedora as my main distro, but that patch is very helpful. Also, there is one for Asus Laptops and Microsoft Surface.
Is it possible for these to be added to CachyOS kernels?

https://gitlab.com/asus-linux
https://github.com/linux-surface/linux-surface/tree/master/patches/6.1
https://github.com/johnfanv2/LenovoLegionLinux

**Comment by ptr1337** [comment]
> Hello!
> 
> I have a Lenovo Legion laptop and in recent months discovered a LenovoLegionLinux kernel patch while testing a version of Nobara in the middle of their list of added features/changes/patches there was one not related to gaming that could be very useful to my system. I use Fedora as my main distro, but that patch is very helpful. Also, there is one for Asus Laptops and Microsoft Surface. Is it possible for these to be added to CachyOS kernels?
> 
> https://gitlab.com/asus-linux https://github.com/linux-surface/linux-surface/tree/master/patches/6.1 https://github.com/johnfanv2/LenovoLegionLinux

Hi @msmafra ,

Sure, we will look into including these patches further. Actually for 6.2 we mostly already did a "feature freeze" since on Sunday will be 6.3 released.

Can you point to which exact surface patches you want to have from https://github.com/linux-surface/linux-surface/tree/master/patches/6.1?
I think we need to try to port them. 

So far I know are the asus-linux patches already included in the upstream 6.2 kernel. So this should be fine.


I will also try to include the Lenovo  patches for 6.3. I will report you here back if it works.

**Comment by msmafra** [comment]
Hello @ptr1337,
Unfortunately, I don't know which Surface Patches should be applied. I thought since I was about to ask for the Lenovo one, asking for the other ones is the correct route.

**Comment by ptr1337** [comment]
Hi @msmafra ,

We have queued the lenovo patch for 6.3, see here https://github.com/CachyOS/linux/commit/326ddce6ba2f52fd0ef68ea525246ba4fe20ca54 .

We need to review the surface patches further, since it is not complete clear, which patches are required for the drivers and which are just a "nice to have". 
Most of these asus patches are already upstreamed.
@ventureoo @sirlucjan and me discussed this like 2 weeks ago and checked it.

**Comment by msmafra** [comment]
> Hi @msmafra ,
> 
> We have queued the lenovo patch for 6.3, see here [CachyOS/linux@326ddce](https://github.com/CachyOS/linux/commit/326ddce6ba2f52fd0ef68ea525246ba4fe20ca54) .
> 
> We need to review the surface patches further, since it is not complete clear, which patches are required for the drivers and which are just a "nice to have". Most of these asus patches are already upstreamed. @ventureoo @sirlucjan and me discussed this like 2 weeks ago and checked it.

Awesome! Thanks a lot.

**Comment by ptr1337** [comment]
Hi @msmafra ,

I checked the linux-surface patches for 6.3 and queued them.
Today I will bring one more "linux-cachyos-rc" patchset for further testing. The only not applied patch right now is the "0012-camera.patch" since it needs a lot of adjusting against 6.3.

Its in the cachyos/linux 6.3/surface branch:
https://github.com/CachyOS/linux/compare/74f662840fe5%5E...96493ed30b8a

**Comment by ptr1337** [comment]
https://github.com/CachyOS/linux-cachyos/commit/c2f0b706bcd2cb7b23ec79b864f9b4857510f433

If you are able to test the RC Kernel - please do it :)

**Comment by msmafra** [comment]
How can I test the RC?

**Comment by ptr1337** [comment]
> How can I test the RC?

Actually if you are on Fedora it would be better if you wait. It would require a lot of adjustments at the .spec.

**Comment by ptr1337** [comment]
@msmafra 

Lenovo Patch is back in 6.3.0-5. This one should come soon to Fedora.
We had some issues with 6.3 but figured it out and were able to bisect down the issue causer.

Here is a PKGBUILD for the GUI only. Maybe you get it ported to Fedora as a .spec, then you can use it proper :)
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lenovolegionlinux-git

**Comment by msmafra** [comment]
-5? Was the LLL the cause?  Thanks again!
I use it by manually installing/applying via the patch_kernel.sh script for LLL, including DKMS. But it seems, that sometimes, it's ignored after a kernel update.
I keep my eyes peeled. :+1:
